# Development Docker Compose Configuration
version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: atcloud-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: atcloud-signup
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - atcloud-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: atcloud-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/atcloud-signup?authSource=admin
      JWT_ACCESS_SECRET: dev_access_secret_change_this_in_production
      JWT_REFRESH_SECRET: dev_refresh_secret_change_this_in_production
      FRONTEND_URL: http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - atcloud-network
    command: npm run dev

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: atcloud-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5001/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - atcloud-network
    command: npm run dev

  # Redis for caching (optional)
  redis:
    image: redis:7.2-alpine
    container_name: atcloud-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - atcloud-network

volumes:
  mongodb_data:
  redis_data:
  backend_uploads:

networks:
  atcloud-network:
    driver: bridge
