export const EVENT_CATEGORIES = [
  "Workshop",
  "Seminar",
  "Training",
  "Conference",
  "Prayer Meeting",
  "Bible Study",
  "Outreach",
  "Youth Ministry",
  "Leadership",
  "Other",
] as const;

export const DEFAULT_EVENT_VALUES = {
  id: "",
  title: "",
  description: "",
  date: "",
  time: "",
  endTime: "",
  location: "",
  type: "",
  organizer: "",
  hostedBy: "@Cloud Marketplace Ministry",
  purpose: "",
  agenda: "",
  format: "",
  disclaimer: "",
  roles: [],
  signedUp: 0,
  totalSlots: 50,
  category: "",
  isHybrid: false,
  zoomLink: "",
  meetingId: "",
  passcode: "",
  requirements: "",
  materials: "",
  createdBy: "",
  createdAt: "",
};

export type EventCategory = (typeof EVENT_CATEGORIES)[number];
