# SPA redirect rules
[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/verify-email/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reset-password/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/change-password/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/check-email"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/logout"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
